spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/test5
        username: sa
        password:
        driver-class-name: org.h2.Driver
#  database connection? ??? ????? ??

    jpa:
        hibernate:
            ddl-auto: create
            # application ?? ??? DB? ?? ??? ? ??? ????.
        properties:
            hibernate:
                    show_sql: true
# jpa sql? system out? ??? ???. ?? system?? ??? ? ?? ?og? ?? ?? ? ??? ?
                    format_sql: true

        database: mysql   # 추가 해준 부분
        database-platform: org.hibernate.dialect.MySQLDialect # 추가 해준 부분

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # jpql??? ????? ?? ?? ?? ???.
    #    hibernate sql? ? ??? ?? ???.

